# Generated by Django 6.0.6 on 2026-07-08 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0002_rename_enddate_tasks_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('contact_number', models.CharField(max_length=150)),
                ('task_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tasks.tasks')),
            ],
        ),
    ]
