# Generated by Django 6.0.6 on 2026-07-03 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='rollNo',
        ),
    ]
