# Generated by Django 6.0.6 on 2026-07-08 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasks',
            old_name='endDate',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='tasks',
            old_name='startDate',
            new_name='start_date',
        ),
    ]
